# Generated by Django 5.2.8 on 2025-11-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("hidden_param_0", models.CharField(blank=True, max_length=255)),
                ("hidden_param_1", models.CharField(blank=True, max_length=255)),
                ("hidden_param_2", models.CharField(blank=True, max_length=255)),
                ("hidden_param_3", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("energyunit", models.CharField(default="eV", max_length=10)),
                ("medium", models.CharField(default="air", max_length=10)),
                ("waveunit", models.CharField(default="angstrom", max_length=10)),
                ("vdwformat", models.CharField(default="default", max_length=20)),
                ("isotopic_scaling", models.CharField(default="on", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="LineList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("commented", models.BooleanField(default=False)),
                ("param_0", models.CharField(blank=True, max_length=255)),
                ("param_1", models.CharField(blank=True, max_length=50)),
                ("param_2", models.CharField(blank=True, max_length=50)),
                ("param_3", models.CharField(blank=True, max_length=50)),
                ("param_4", models.CharField(blank=True, max_length=50)),
                ("param_5", models.CharField(blank=True, max_length=50)),
                ("param_6", models.CharField(blank=True, max_length=50)),
                ("param_7", models.CharField(blank=True, max_length=50)),
                ("param_8", models.CharField(blank=True, max_length=50)),
                ("param_9", models.CharField(blank=True, max_length=50)),
                ("param_10", models.CharField(blank=True, max_length=50)),
                ("param_11", models.CharField(blank=True, max_length=50)),
                ("param_12", models.CharField(blank=True, max_length=50)),
                ("param_13", models.CharField(blank=True, max_length=50)),
                ("param_14", models.TextField(blank=True)),
                ("mod_comment", models.BooleanField(default=False)),
                ("mod_param_1", models.BooleanField(default=False)),
                ("mod_param_2", models.BooleanField(default=False)),
                ("mod_param_3", models.BooleanField(default=False)),
                ("mod_param_4", models.BooleanField(default=False)),
                ("mod_param_5", models.BooleanField(default=False)),
                ("mod_param_6", models.BooleanField(default=False)),
                ("mod_param_7", models.BooleanField(default=False)),
                ("mod_param_8", models.BooleanField(default=False)),
                ("mod_param_9", models.BooleanField(default=False)),
                ("mod_param_10", models.BooleanField(default=False)),
                ("mod_param_11", models.BooleanField(default=False)),
                ("mod_param_12", models.BooleanField(default=False)),
                ("mod_param_13", models.BooleanField(default=False)),
                (
                    "personal_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linelists",
                        to="vald.personalconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["list_id"],
            },
        ),
    ]
