# Generated by Django 5.2.8 on 2025-11-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0003_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linelist',
            name='personal_config',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.DeleteModel(
            name='LineList',
        ),
        migrations.DeleteModel(
            name='PersonalConfig',
        ),
    ]
