# Generated by Django 5.2.8 on 2025-11-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0004_remove_linelist_personal_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_name',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='vald.user'),
        ),
    ]
