# Generated by Django 5.2.8 on 2025-11-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0005_request_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energyunit', models.CharField(choices=[('eV', 'eV'), ('cm', 'cm⁻¹')], default='eV', max_length=10)),
                ('medium', models.CharField(choices=[('air', 'Air (λ > 200nm)'), ('vacuum', 'Vacuum')], default='air', max_length=10)),
                ('waveunit', models.CharField(choices=[('angstrom', 'Ångström'), ('nm', 'Nanometers'), ('cm', 'cm⁻¹')], default='angstrom', max_length=10)),
                ('vdwformat', models.CharField(choices=[('default', 'Default (single value)'), ('extended', 'Extended format')], default='default', max_length=20)),
                ('isotopic_scaling', models.CharField(choices=[('on', 'Apply isotopic scaling'), ('off', 'No isotopic scaling')], default='on', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='vald.user')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
