# Generated by Django 5.2.8 on 2025-11-27 10:26

from django.db import migrations


def fix_cm_to_1_per_cm(apps, schema_editor):
    """Update 'cm' to '1/cm' for energyunit and waveunit fields"""
    UserPreferences = apps.get_model('vald', 'UserPreferences')

    # Update energyunit: 'cm' → '1/cm'
    UserPreferences.objects.filter(energyunit='cm').update(energyunit='1/cm')

    # Update waveunit: 'cm' → '1/cm'
    UserPreferences.objects.filter(waveunit='cm').update(waveunit='1/cm')


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0006_user_preferences'),
    ]

    operations = [
        migrations.RunPython(fix_cm_to_1_per_cm, migrations.RunPython.noop),
    ]
