# Generated by Django 5.2.9 on 2025-12-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0007_fix_cm_to_1_per_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Path to linelist file, e.g., '/CVALD3/ATOMS/Fe_NBS_cut_V3'", max_length=255, unique=True)),
                ('name', models.CharField(help_text="Description, e.g., 'Fe: NBS data'", max_length=200)),
                ('element_min', models.IntegerField(help_text='Minimum element code (e.g., 326 for Fe I)')),
                ('element_max', models.IntegerField(help_text='Maximum element code (e.g., 334 for Fe IX)')),
                ('is_molecular', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='Data source (NBS, Kurucz, NIST, etc.)', max_length=100)),
                ('default_priority', models.IntegerField(default=1000)),
                ('default_rank_wl', models.IntegerField(default=3, help_text='Wavelength quality rank (1-9)')),
                ('default_rank_gf', models.IntegerField(default=3, help_text='Oscillator strength quality rank')),
                ('default_rank_rad', models.IntegerField(default=3, help_text='Radiative damping quality rank')),
                ('default_rank_stark', models.IntegerField(default=3, help_text='Stark damping quality rank')),
                ('default_rank_waals', models.IntegerField(default=3, help_text='Van der Waals damping quality rank')),
                ('default_rank_lande', models.IntegerField(default=3, help_text='Lande factor quality rank')),
                ('default_rank_term', models.IntegerField(default=3, help_text='Term designation quality rank')),
                ('default_rank_ext_vdw', models.IntegerField(default=3, help_text='Extended VdW quality rank')),
                ('default_rank_zeeman', models.IntegerField(default=3, help_text='Zeeman data quality rank')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this linelist is currently available')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linelist',
                'verbose_name_plural': 'Linelists',
                'ordering': ['default_priority', 'path'],
            },
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='energyunit',
            field=models.CharField(choices=[('eV', 'eV'), ('1/cm', 'cm⁻¹')], default='eV', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='waveunit',
            field=models.CharField(choices=[('angstrom', 'Ångström'), ('nm', 'Nanometers'), ('1/cm', 'cm⁻¹')], default='angstrom', max_length=10),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default config for this user')),
                ('wl_window_ref', models.FloatField(default=0.05, help_text='Wavelength window reference (Å)')),
                ('wl_ref', models.FloatField(default=5000.0, help_text='Reference wavelength (Å)')),
                ('max_ionization', models.IntegerField(default=9, help_text='Maximum ionization stage')),
                ('max_excitation_eV', models.FloatField(default=150.0, help_text='Maximum excitation potential (eV)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner (NULL = system config)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='vald.user')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigLinelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Read order (lower = higher priority)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this linelist is active (False = commented out)')),
                ('mergeable', models.IntegerField(choices=[(0, 'Mergeable'), (1, 'Standalone (never merge)'), (2, 'Replacement list (always merge)')], default=0)),
                ('replacement_window', models.FloatField(default=0.05, help_text='Wavelength tolerance for merging (Å)')),
                ('rank_wl', models.IntegerField(default=3)),
                ('rank_gf', models.IntegerField(default=3)),
                ('rank_rad', models.IntegerField(default=3)),
                ('rank_stark', models.IntegerField(default=3)),
                ('rank_waals', models.IntegerField(default=3)),
                ('rank_lande', models.IntegerField(default=3)),
                ('rank_term', models.IntegerField(default=3)),
                ('rank_ext_vdw', models.IntegerField(default=3)),
                ('rank_zeeman', models.IntegerField(default=3)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vald.config')),
                ('linelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vald.linelist')),
            ],
            options={
                'verbose_name': 'Config Linelist',
                'verbose_name_plural': 'Config Linelists',
                'ordering': ['priority'],
                'unique_together': {('config', 'linelist')},
            },
        ),
        migrations.AddField(
            model_name='config',
            name='linelists',
            field=models.ManyToManyField(related_name='configs', through='vald.ConfigLinelist', to='vald.linelist'),
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_config_per_user'),
        ),
    ]
