# Generated by Django 5.2.9 on 2026-08-03 06:02

from django.db import migrations, models


def backfill_token_created_at(apps, schema_editor):
    """Give already-issued tokens an issue time so they are not invalidated.

    token_is_valid() treats a missing issue time as expired, which would break
    activation and reset links that are legitimately in flight right now. Using
    updated_at is the closest available approximation - the token was set by a
    save() - so those links keep working and then expire normally.
    """
    User = apps.get_model('vald', 'User')
    for user in User.objects.filter(activation_token__isnull=False,
                                    token_created_at__isnull=True):
        User.objects.filter(pk=user.pk).update(token_created_at=user.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0008_add_config_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_token_created_at,
                             migrations.RunPython.noop),
    ]
