# Generated by Django 5.2.17 on 2026-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0011_drop_configs_identical_to_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linelist',
            name='default_rank_wl',
            field=models.IntegerField(default=3, help_text='Wavelength quality rank (0-9)'),
        ),
    ]
