# Generated by Django 5.2.17 on 2026-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0012_rank_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='snapshot_at',
            field=models.DateTimeField(blank=True, help_text='Source file mtime for an imported config; blank if created here', null=True),
        ),
    ]
