# Generated by Django 5.2.17 on 2026-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0014_config_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, help_text='What this configuration contains, shown beneath the linelist configuration menu on the request forms when it is selected'),
        ),
    ]
