# Generated by Django 5.2.17 on 2026-08-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vald', '0015_config_description_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='snapshot_of',
            field=models.ForeignKey(blank=True, help_text='System config this personal configuration was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='vald.config'),
        ),
    ]
