"""
Django settings for vald_web project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ---------------------------------------------------------------------------
# Per-site configuration.
#
# Everything a VALD mirror needs to change lives in secrets.txt (read by
# systemd via EnvironmentFile= and by bin/vald-manage), so this file is
# identical on every site and does not conflict on pull. See
# secrets.txt.example for the full list; the defaults below are the Uppsala
# values, so an existing deployment behaves the same with no secrets.txt
# change. This mirrors what old/config/site_config_local.php.template did for the
# PHP interface.
# ---------------------------------------------------------------------------

def _env_list(name, default):
    """Comma-separated environment variable -> list of non-empty strings."""
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def _env_bool(name, default='False'):
    return os.environ.get(name, default).strip().lower() in ('true', '1', 'yes')


# see secrets.txt
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG')

ALLOWED_HOSTS = _env_list('VALD_ALLOWED_HOSTS', 'vald.astro.uu.se,localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    "vald",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vald_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vald_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        # Job threads across several gunicorn workers all write status updates;
        # WAL lets readers run during a write and the timeout replaces the 5s
        # default that otherwise surfaces as "database is locked".
        "OPTIONS": {
            "timeout": 20,
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}

# Cache configuration for rate limiting.
# Must be shared across gunicorn workers - LocMemCache is per-process, so every
# rate limit was silently multiplied by the worker count.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(BASE_DIR / 'cache' / 'ratelimit'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
USE_I18N = False
TIME_ZONE = "Europe/Stockholm"
USE_TZ = True

## DEPLOY via reverse proxy
# Sub-path the app is served under, without a trailing slash. Set it empty to
# serve from the site root - Django checks `is not None`, so '' is honoured and
# means "no prefix". The cookie paths and STATIC_URL below derive from it, so
# this is the only place the prefix appears.
#
# NB changing it invalidates every existing session and CSRF token, because the
# cookie paths change with it. Expect logged-in users to be signed out.
FORCE_SCRIPT_NAME = os.environ.get('VALD_URL_PREFIX', '/new')

USE_X_FORWARDED_HOST = True
APPEND_SLASH = False  # Avoid redirect issues with reverse proxy
CSRF_COOKIE_PATH = FORCE_SCRIPT_NAME or '/'
SESSION_COOKIE_PATH = FORCE_SCRIPT_NAME or '/'
CSRF_TRUSTED_ORIGINS = _env_list('VALD_CSRF_TRUSTED_ORIGINS', 'https://vald.astro.uu.se')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# Header consulted by vald.ratelimit.client_ip (rightmost entry is used).
# Do NOT use RATELIMIT_IP_META_KEY here - it reads the header verbatim and is
# spoofable, since the proxy appends rather than overwrites.
RATELIMIT_CLIENT_IP_HEADER = 'HTTP_X_FORWARDED_FOR'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = f"{FORCE_SCRIPT_NAME}/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Where collectstatic puts files
# NB: VALD_FTP_DIR (results) must never sit inside any of these trees, or
# collectstatic would publish user results as static files (R19). It lives under
# $VALD_HOME/WWW, well outside BASE_DIR - keep it that way.
STATICFILES_DIRS = [BASE_DIR / "style", BASE_DIR / "public_html"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration - uses system sendmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = os.environ.get('VALD_FROM_EMAIL', 'vald@physics.uu.se')
VALD_ADMIN_EMAIL = os.environ.get('VALD_ADMIN_EMAIL', 'thomas.marquart@physics.uu.se')
VALD_WEBMASTER_EMAIL = os.environ.get('VALD_WEBMASTER_EMAIL', 'thomas.marquart@physics.uu.se')


# VALD-specific configuration
VALD_HOME = Path(os.getenv('VALD_HOME', ''))

# Validate VALD_HOME is set and exists
if not VALD_HOME or str(VALD_HOME) == '.':
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "VALD_HOME environment variable must be set. "
        "Set it in your systemd service file or shell environment."
    )
if not VALD_HOME.exists():
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        f"VALD_HOME directory does not exist: {VALD_HOME}. "
        "Please check the path in your VALD_HOME environment variable."
    )

PERSCONFIG_DIR = BASE_DIR / 'config' / 'personal_configs'
DOCUMENTATION_DIR = BASE_DIR / 'documentation'
NEWS_DIR = BASE_DIR / 'news'
SITENAME = os.environ.get('VALD_SITENAME', 'VALD Uppsala')
# Base URL without the sub-path prefix; completion emails append
# FORCE_SCRIPT_NAME themselves (reverse() omits it in a background thread).
SITE_URL = os.environ.get('VALD_SITE_URL', 'https://vald.astro.uu.se')

# Backend processing configuration
VALD_BIN = VALD_HOME / 'bin'
VALD_WORKING_DIR = BASE_DIR / 'working'  # Working directory for request processing
VALD_FTP_DIR = VALD_HOME / 'WWW' / 'public_html' / 'FTP'  # Output directory for results
# Extractions running at once: the size of the JobQueue thread pool in
# backend.py. NOT a process count - gunicorn deliberately runs a single worker
# process (vald.service), because the queue lives in that process's memory and
# N processes would each get their own, making the real ceiling N x this.
VALD_MAX_THREADS = 5  # Parallel job executions (FIFO queue)
VALD_MAX_QUEUE_SIZE = 10  # Maximum pending jobs in queue before rejecting new requests
# Maximum output lines per request, written as pres_in line 2 (R29).
# Was previously only a getattr() fallback in job_runner, defined nowhere.
# For reference, legacy parserequest.c used two values chosen by delivery
# method: MAX_LINES_PER_FTP (100000) and MAX_LINES_PER_REQUEST (1000, email).
# We deliberately keep a single 500000 for both - see finds.md R29/R33.
VALD_MAX_LINES_PER_REQUEST = 500000

# Wall-clock budget for one job pipeline, in seconds
VALD_JOB_TIMEOUT = 3600

# Most extraction requests one user may have in flight at once. The global
# admission limit is VALD_MAX_QUEUE_SIZE; without a per-user cap one user
# could occupy all of it and everyone else got "Server is busy" (R5).
VALD_MAX_REQUESTS_PER_USER = 5

# Submission rate per user (django-ratelimit syntax). The in-flight cap above
# is the real protection; this just stops a scripted loop.
VALD_SUBMIT_RATE = '120/h'

# Rate limit on the Django admin login (django-ratelimit syntax). The admin is
# publicly reachable and Django does not throttle it at all on its own.
VALD_ADMIN_LOGIN_RATE = '10/h'

# Session lifetime. Django's default is two weeks. Sessions are revalidated
# against the database on every request (see views.get_current_user), so this
# only bounds how long an idle, untouched cookie stays usable.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week

# Minimum gap between "job queue full" alerts to the webmaster. The alert fires
# once per rejected submission, and a full queue produces those in bursts.
VALD_QUEUE_FULL_COOLDOWN = 1800  # 30 minutes

# Completion emails attach the result file. Above this size, skip the
# attachment and rely on the download links in the body - some mail servers
# bounce large attachments, which would leave the user with no notification at
# all despite the files being ready (R33).
VALD_MAX_EMAIL_ATTACH_BYTES = 5 * 1024 * 1024  # 5 MB

# How long activation and password-reset links stay usable. The reset email
# claims 7 days; before this existed the tokens never expired at all (R6).
VALD_TOKEN_MAX_AGE_DAYS = 7
# How long result files are kept before cleanup_old_results deletes them. Used
# for the cleanup command's default --age, the "available for N hours" wording in
# completion emails, and to tell expired results apart from missing ones (R21).
VALD_RESULT_RETENTION_DAYS = 2




# Logging. Without this, unhandled 500s and every logger.exception() call in the
# job pipeline went nowhere - Django only configures a console handler while
# DEBUG is on. gunicorn is started with --error-logfile - so stderr reaches
# journald; use `journalctl -u vald` to read it.
ADMINS = [('VALD webmaster', VALD_WEBMASTER_EMAIL)]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'include_html': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Unhandled exceptions in views
        'django.request': {
            'handlers': ['console', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Our own modules: job pipeline, request processing
        'vald': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
