"""
Django settings for vald_web project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# see secrets.txt
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1')

ALLOWED_HOSTS = ['vald.astro.uu.se','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "vald",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vald_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vald_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
USE_I18N = False
TIME_ZONE = "Europe/Stockholm"
USE_TZ = True

## DEPLOY via reverse proxy
FORCE_SCRIPT_NAME = '/new'
USE_X_FORWARDED_HOST = True
APPEND_SLASH = False  # Avoid redirect issues with reverse proxy
CSRF_COOKIE_PATH = '/new'
SESSION_COOKIE_PATH = '/new'
CSRF_TRUSTED_ORIGINS = ['https://vald.astro.uu.se']
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional security headers
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/new/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Where collectstatic puts files
STATICFILES_DIRS = [BASE_DIR / "style", BASE_DIR / "public_html"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration - uses system sendmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'vald@physics.uu.se'
VALD_ADMIN_EMAIL = 'thomas.marquart@physics.uu.se'
VALD_WEBMASTER_EMAIL = 'thomas.marquart@physics.uu.se'
# Use os.environ["VALD_WEBMASTER_PASSWORD"] and set it in secrets.txt, if needed
# It gets read by systemd service file.


# VALD-specific configuration
VALD_HOME = Path(os.getenv('VALD_HOME', ''))

# Validate VALD_HOME is set and exists
if not VALD_HOME or str(VALD_HOME) == '.':
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "VALD_HOME environment variable must be set. "
        "Set it in your systemd service file or shell environment."
    )
if not VALD_HOME.exists():
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        f"VALD_HOME directory does not exist: {VALD_HOME}. "
        "Please check the path in your VALD_HOME environment variable."
    )

CLIENTS_REGISTER = BASE_DIR / 'config' / 'clients.register'
CLIENTS_REGISTER_LOCAL = BASE_DIR / 'config' / 'clients.register.local'
PERSCONFIG_DIR = BASE_DIR / 'config' / 'personal_configs'
PERSCONFIG_DEFAULT = BASE_DIR / 'config' / 'default.cfg'
HTMLCONFIG_DEFAULT = BASE_DIR / 'config' / 'htmldefault.cfg'
DOCUMENTATION_DIR = BASE_DIR / 'documentation'
NEWS_DIR = BASE_DIR / 'news'
SITENAME = 'VALD Uppsala'
SITE_URL = 'https://vald.astro.uu.se'  # Base URL (reverse() adds the /new prefix)
MAINTENANCE = False

# Backend processing configuration
VALD_BIN = VALD_HOME / 'bin'
VALD_SHOWLINE_BIN = VALD_BIN / 'showline4.1'  # parserequest binary
VALD_PARSEREQUEST_BIN = VALD_BIN / 'parserequest'  # parserequest binary
VALD_WORKING_DIR = BASE_DIR / 'working'  # Working directory for request processing
VALD_FTP_DIR = VALD_HOME / 'WWW' / 'public_html' / 'FTP'  # Output directory for results
VALD_MAX_WORKERS = 5  # Maximum parallel job executions (FIFO queue)
VALD_MAX_QUEUE_SIZE = 10  # Maximum pending jobs in queue before rejecting new requests
