"""
Django settings for vald_web project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-b78@6-7-x-+3y9cu82==f(4q!juta8elrb8hjp$y4plpw6ale3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['vald.astro.uu.se','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "vald",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vald_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vald_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}

# Cache configuration for rate limiting (see settings_deploy for why not LocMem)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(BASE_DIR / 'cache' / 'ratelimit'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Stockholm"

USE_I18N = False
# ISO dates, English language. A locale format module beats the
# DATETIME_FORMAT setting, so overriding that setting alone does nothing -
# see vald_web/formats/en/formats.py.
FORMAT_MODULE_PATH = 'vald_web.formats'

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "style"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration (SMTP with STARTTLS)
# Configure these via environment variables in production
# For testing: use EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp.fastmail.com'  # Change this to your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # Set via environment variable
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Set via environment variable
DEFAULT_FROM_EMAIL = 'vald@tmy.se'
VALD_ADMIN_EMAIL = 'vald@tmy.se'
VALD_WEBMASTER_EMAIL = 'vald@tmy.se'

# VALD-specific configuration
VALD_HOME = Path(os.getenv('VALD_HOME', '/home/tom/VALD3'))
PERSCONFIG_DIR = BASE_DIR / 'config' / 'personal_configs'
NEWS_DIR = BASE_DIR / 'news'
SITENAME = 'VALD'
SITE_URL = 'http://localhost:8000'  # Base URL for email links (update for production)

# Backend processing configuration
VALD_BIN = VALD_HOME / 'bin'
VALD_WORKING_DIR = BASE_DIR / 'working'  # Working directory for request processing
# Results must live OUTSIDE any STATICFILES_DIRS tree, or collectstatic would
# publish them (R19). Here that is public_html/FTP, matching the layout the
# server serves, and it is safe only because dev's STATICFILES_DIRS is just
# style/ - unlike settings_deploy, which adds public_html and therefore keeps
# results under VALD_HOME instead. Adding public_html here would re-open R19.
VALD_FTP_DIR = BASE_DIR / 'public_html' / 'FTP'  # Output directory for results
# Extractions running at once: the size of the JobQueue thread pool in
# backend.py. NOT a process count - gunicorn deliberately runs a single worker
# process (vald.service), because the queue lives in that process's memory and
# N processes would each get their own, making the real ceiling N x this.
VALD_MAX_THREADS = 1  # Parallel job executions (FIFO queue). Prod uses 5.
VALD_MAX_QUEUE_SIZE = 10  # Maximum pending jobs in queue before rejecting new requests
# Maximum output lines per request, written as pres_in line 2 (R29).
# Was previously only a getattr() fallback in job_runner, defined nowhere.
# For reference, legacy parserequest.c used two values chosen by delivery
# method: MAX_LINES_PER_FTP (100000) and MAX_LINES_PER_REQUEST (1000, email).
# We deliberately keep a single 500000 for both - see finds.md R29/R33.
VALD_MAX_LINES_PER_REQUEST = 500000

# Wall-clock budget for one job pipeline, in seconds
VALD_JOB_TIMEOUT = 3600

# Most extraction requests one user may have in flight at once. The global
# admission limit is VALD_MAX_QUEUE_SIZE; without a per-user cap one user
# could occupy all of it and everyone else got "Server is busy" (R5).
VALD_MAX_REQUESTS_PER_USER = 5

# Submission rate per user (django-ratelimit syntax). The in-flight cap above
# is the real protection; this just stops a scripted loop.
VALD_SUBMIT_RATE = '120/h'

# Rate limit on the Django admin login (django-ratelimit syntax). The admin is
# publicly reachable and Django does not throttle it at all on its own.
VALD_ADMIN_LOGIN_RATE = '10/h'

# Session lifetime. Django's default is two weeks. Sessions are revalidated
# against the database on every request (see views.get_current_user), so this
# only bounds how long an idle, untouched cookie stays usable.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week

# Minimum gap between "job queue full" alerts to the webmaster.
VALD_QUEUE_FULL_COOLDOWN = 1800  # 30 minutes

# Requests left unfinished by a restart, re-run for their owners when the
# application next starts (vald/startup.py). Above this many, they are failed
# and the webmaster is mailed instead: replaying a flood on boot would fill
# VALD_MAX_QUEUE_SIZE and start rejecting live users.
VALD_STRANDED_RERUN_MAX = 5

# A request still 'processing' this many times VALD_JOB_TIMEOUT is stuck: the
# pipeline deadline has passed several times over. Reported by
# cleanup_old_results, which runs in its own process and so cannot ask the queue
# what is really running - age is all it has, hence the generous multiple.
VALD_STUCK_JOB_TIMEOUT_FACTOR = 2

# Completion emails attach the result file. Above this size, skip the
# attachment and rely on the download links in the body - some mail servers
# bounce large attachments, which would leave the user with no notification at
# all despite the files being ready (R33).
VALD_MAX_EMAIL_ATTACH_BYTES = 5 * 1024 * 1024  # 5 MB

# How long activation and password-reset links stay usable. The reset email
# claims 7 days; before this existed the tokens never expired at all (R6).
VALD_TOKEN_MAX_AGE_DAYS = 7
# How long result files are kept before cleanup_old_results deletes them. Used
# for the cleanup command's default --age, the "available for N hours" wording in
# completion emails, and to tell expired results apart from missing ones (R21).
VALD_RESULT_RETENTION_DAYS = 2




# Logging - console only in development (see settings_deploy for production)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'vald': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
